apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: jerh-pipeline
spec:
  tasks:
    - name: task1
      taskRef:
        name: task1
    - name: cleanup
      taskRef:
        name: cleanup