apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: message
      description: the message
    - name: repository
      description: the git repo
    - name: apikey
      description: the ibmcloud api key
  tasks:
    - name: pipeline-write-task
      taskRef:
        name: build-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: message
          value: $(params.message)
        - name: repository
          value: $(params.repository)
        - name: apikey
          value: $(params.apikey)
    - name: pipeline-read-task
      runAfter: [pipeline-write-task]
      taskRef:
        name: read-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)