apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: echo-props-pipeline
spec:
  params:
    - name: quote
      description: simple quoted property
      default: "TESTQUOTE"
    - name: noquote
      description: simple unquoted property
      default: "TESTNOQUOTE"
  tasks:
    - name: echo-task
      taskRef:
        name: echo-props
      params:
        - name: quote
          value: $(params.quote)
        - name: noquote
          value: $(params.noquote)
