apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: echo-props-pipeline
spec:
  params:
    - name: quote
      description: simple quoted property
      default: TESTQUOTE
    - name: noquote
      description: simple unquoted property
      default: TESTNOQUOTE
    - name: environment_value
      description: A value from the pipeline level, trigger level or run level
      default: BLOOPER  
  tasks:
    - name: echo-task
      taskRef:
        name: echo-props
      params:
        - name: quote
          value: $(params.quote)
        - name: noquote
          value: $(params.noquote)
        - name: environment_value
          value: $(params.environment_value)
    - name: cm-echo-task
      taskRef:
        name: cm-echo-props
      params:
        - name: quote
          value: $(params.quote)
    - name: env-echo-task
      taskRef: 
        name: cm-all-props
    - name: cm-secrets-all-props
      taskRef:
          name: cm-secrets-props    
    - name: call-external-pipeline
      taskRef:
        name: call-the-pipe-cleaner    