apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 1 - Step 1 Changed';
          apt-get -y install iputils-ping;
          ping -c 5 -W 5 greenwell-app.eu-de.mybluemix.net;
    - name: task-one-step-two
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 1 - Step 2 Changed';
          apt-get -y install curl;
          curl https://greenwell-app.eu-de.mybluemix.net/health;