apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-props
spec:
  inputs:
    params:
      - name: quote
        description: Simple quoted property
      - name: noquote
        description: Simple un-quoted property
      - name: environment_value
        description: Value from pipeline, trigger, or run property    
  steps:
    - name: show-props
      image: ubuntu
      env:
        - name: QUOTE
          value: $(inputs.params.quote)
        - name: NOQUOTE
          value: $(inputs.params.noquote)
        - name: ENVIRONMENT_VALUE
          value: $(inputs.params.environment_value)    
      command: ["/bin/bash", "-c"]
      args:
        - echo "This is what I can see man";
          echo $QUOTE;
          echo $NOQUOTE;
          echo "This is what I was sent";
          echo $ENVIRONMENT_VALUE;
          echo "Nothing else to see here"
