apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Greenwell Site - Health Check TOO';
          apt-get -qq update > /dev/null; apt-get -qq -y install curl > /dev/null;
          alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
    - name: task-two
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['devops.cloud.ibm.com/buildNumber']
      command: ["bash", "-c"]
      args:
        - echo "SHAZBOT";
          echo $BUILD_NUMBER;
          echo "FINISHED AGAIN"     
