apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 1 - Step 1 Changed';
          apt-get update; apt-get -y install iputils-ping;
          ping -c 5 -W 5 greenwell-app.eu-de.mybluemix.net;
    - name: task-one-step-two
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 1 - Step 2 Changed';
          apt-get update; apt-get -y install curl;
          alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS"; exit 0;
          else echo "TEST FAIL"; exit 1;
          fi