apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Greenwell Site - Health Check';
          apt-get update; apt-get -y install curl;
          alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS"; exit 1;
          else echo "TEST FAIL"; exit 1;
          fi