apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 1 - Step 1 Changed';
          apt-get update; apt-get -y install iputils-ping;
          ping greenwell-app.eu-de.mybluemix.net;
    - name: task-one-step-two
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - echo 'Task 1 - Step 2 Changed';
          apt-get update; apt-get -y install curl;
          curl https://greenwell-app.eu-de.mybluemix.net/health;
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
    - name: task-two-step-one
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - echo 'Task 2 - Step 1 Changed';
          apt-get update; apt-get -y install iputils-ping;
          ping greenwell-app.eu-de.mybluemix.net;
    - name: task-two-step-two
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Task 2 - Step 2 Changed';
          apt-get update; apt-get -y install curl;
          curl https://greenwell-app.eu-de.mybluemix.net/health;